const tintColorLight = '#0058bb';
const tintColorDark = '#6c9fff';

export const Colors = {
  light: {
    text: '#2d2f31',
    background: '#f6f6f8',
    tint: tintColorLight,
    icon: '#5a5c5d',
    tabIconDefault: '#5a5c5d',
    tabIconSelected: tintColorLight,
    primary: '#0058bb',
    primaryContainer: '#6c9fff',
    secondary: '#b4005d',
    secondaryContainer: '#ffc1d1',
    tertiary: '#006859',
    tertiaryContainer: '#26fedc',
    surface: '#f6f6f8',
    surfaceVariant: '#dbdde0',
    onSurface: '#2d2f31',
    onSurfaceVariant: '#5a5c5d',
    surfaceContainerLow: '#f0f1f3',
    surfaceContainer: '#e7e8ea',
    surfaceContainerHigh: '#e1e2e5',
    surfaceContainerHighest: '#dbdde0',
    outline: '#757779',
    outlineVariant: '#acadaf',
    error: '#b31b25',
  },
  dark: {
    text: '#f0f1f3',
    background: '#0c0e10',
    tint: tintColorDark,
    icon: '#9c9d9f',
    tabIconDefault: '#9c9d9f',
    tabIconSelected: tintColorDark,
    primary: '#6c9fff',
    primaryContainer: '#004ca4',
    secondary: '#ffacc4',
    secondaryContainer: '#9f0051',
    tertiary: '#00efce',
    tertiaryContainer: '#005a4d',
    surface: '#0c0e10',
    surfaceVariant: '#2d2f31',
    onSurface: '#f0f1f3',
    onSurfaceVariant: '#9c9d9f',
    surfaceContainerLow: '#1c1e21',
    surfaceContainer: '#2d2f31',
    surfaceContainerHigh: '#3e4043',
    surfaceContainerHighest: '#4f5154',
    outline: '#9c9d9f',
    outlineVariant: '#5a5c5d',
    error: '#fb5151',
  },
};
