# GitHub Actions deployment pipeline for Azure Web App (Backend only)

name: Deploy Backend to Azure

on:
  workflow_run:
    workflows: ["Backend CI/CD Pipeline"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest

    steps:
      # Download backend artifact (zipped)
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: .

      # Verify downloaded file
      - name: Check downloaded file
        run: |
          if [ ! -f backend.zip ]; then
            echo "ERROR: backend.zip is missing!"
            exit 1
          fi
          unzip -l backend.zip

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure App Service using zipped artifact
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: tazq-backend-api
          package: backend.zip
