name: Deploy Backend to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: tazq-backend-api
  AZURE_WEBAPP_PACKAGE_PATH: Tazq-Backend/publish
  DOTNET_VERSION: 8.0.x
  WORKING_DIRECTORY: Tazq-Backend
  API_IMPORT_SPECIFICATION_PATH: Tazq-Backend/publish/swagger.json
  API_IMPORT_DLL: Tazq-Backend/bin/Release/net8.0/Tazq-Backend.dll
  API_IMPORT_VERSION: v1
  JWT_KEY: ${{ secrets.JWT_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Entity Framework CLI
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore Dependencies
        run: |
          dotnet nuget locals all --clear
          dotnet restore ${{ env.WORKING_DIRECTORY }}

      - name: Build
        run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration Release --no-restore

      - name: Apply Database Migrations
        run: |
          echo "Applying database migrations..."
          dotnet ef database update --project ${{ env.WORKING_DIRECTORY }} --context AppDbContext
          echo "Migrations applied successfully."

      - name: Test
        run: dotnet test ${{ env.WORKING_DIRECTORY }} --no-build --configuration Release

      - name: Ensure Publish Directory Exists
        run: mkdir -p ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Publish Backend
        run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Debug - List Published Files
        run: ls -la ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Install Swashbuckle CLI
        run: |
          echo "Installing Swashbuckle CLI..."
          dotnet tool update --global Swashbuckle.AspNetCore.Cli --version 6.4.0 || \
          dotnet tool install --global Swashbuckle.AspNetCore.Cli --version 6.4.0
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          export PATH="$HOME/.dotnet/tools:$PATH"
          echo "Swashbuckle CLI installed successfully"

      - name: Start API for OpenAPI Generation
        run: |
          echo "Starting API in the background..."
          nohup dotnet run --project ${{ env.WORKING_DIRECTORY }} --no-build --urls="http://localhost:5000" > output.log 2>&1 &
          sleep 15
          echo "API started successfully."

      - name: Generate Open API Specification Document
        run: |
          echo "Checking if Swagger JSON is accessible..."
          curl --retry 5 --retry-delay 5 --retry-connrefused -s http://localhost:5000/swagger/v1/swagger.json > ${{ env.API_IMPORT_SPECIFICATION_PATH }}
          echo "Generated Open API Specification Document at ${{ env.API_IMPORT_SPECIFICATION_PATH }}"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.TAZQ_BACKEND_APIM_SPN }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Logout from Azure
        run: az logout
