# Deployment pipeline for deploying backend artifact to Azure Web App

name: Deploy Backend to Azure Web App

on:
  workflow_run:
    workflows: ["Backend CI/CD Pipeline"]
    types:
      - completed

env:
  AZURE_WEBAPP_NAME: tazq-backend-api
  PUBLISH_DIR: Tazq-Backend/publish

jobs:
  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest

    steps:
      # Download build artifact
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: ${{ env.PUBLISH_DIR }}

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web App
      - name: Deploy backend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.PUBLISH_DIR }}
