# GitHub Actions CI/CD pipeline for deploying .NET backend to Azure App Service
# Includes EF migrations, tests, Swagger JSON generation, and artifact upload

name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  WORKING_DIRECTORY: Tazq-Backend
  DOTNET_VERSION: 8.0.x
  AZURE_WEBAPP_NAME: tazq-backend-api
  AZURE_WEBAPP_PACKAGE_PATH: Tazq-Backend/publish
  API_IMPORT_SPECIFICATION_PATH: Tazq-Backend/publish/swagger.json
  API_IMPORT_DLL: Tazq-Backend/bin/Release/net8.0/Tazq-Backend.dll
  API_IMPORT_VERSION: v1

jobs:
  build:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      # Checkout project repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Install EF Core & Swashbuckle CLI
      - name: Install tools
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool update --global Swashbuckle.AspNetCore.Cli --version 6.4.0 || dotnet tool install --global Swashbuckle.AspNetCore.Cli --version 6.4.0
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # Restore NuGet packages
      - name: Restore packages
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}/Tazq-Backend.csproj --force --ignore-failed-sources

      # Build project
      - name: Build app
        run: dotnet build ${{ env.WORKING_DIRECTORY }}/Tazq-Backend.csproj --configuration Release --no-restore

      # Apply EF Core migrations
      - name: Apply EF migrations
        run: |
          dotnet ef database update --project ${{ env.WORKING_DIRECTORY }}/Tazq-Backend.csproj --context AppDbContext
          echo "Migrations applied."

      # Run test suite
      - name: Run tests
        run: dotnet test ${{ env.WORKING_DIRECTORY }}/Tazq-Backend.csproj --no-build --configuration Release

      # Publish the application
      - name: Publish app
        run: dotnet publish ${{ env.WORKING_DIRECTORY }}/Tazq-Backend.csproj --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Start backend for Swagger export
      - name: Start backend locally
        run: |
          dotnet run --no-build --urls="http://0.0.0.0:7031" --project ${{ env.WORKING_DIRECTORY }} > output.log 2>&1 &
          sleep 20

      # Check Swagger JSON availability
      - name: Check Swagger readiness
        run: |
          for i in {1..12}; do
            STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:7031/swagger/v1/swagger.json)
            if [ "$STATUS_CODE" -eq 200 ]; then
              echo "Swagger JSON is available."
              exit 0
            fi
            echo "Retrying Swagger check (HTTP $STATUS_CODE)..."
            sleep 5
          done
          echo "Swagger JSON unavailable." && cat output.log && exit 1

      # Export Swagger JSON
      - name: Export Swagger JSON
        run: curl -s http://localhost:7031/swagger/v1/swagger.json > "${{ env.API_IMPORT_SPECIFICATION_PATH }}"

      # Upload artifact
      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    name: Deploy Backend to Azure
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production

    steps:
      # Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: .

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
