# Azure Web Apps Deploy Pipeline
name: Build and deploy ASP.Net Core app to Azure Web App - tazq-backend-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies (Only Backend)
        run: |
          dotnet restore Tazq-Backend/Tazq-Backend.csproj --force --ignore-failed-sources

      - name: Build Backend Only
        run: |
          dotnet build Tazq-Backend/Tazq-Backend.csproj --configuration Release --no-restore

      - name: Ensure Publish Directory Exists
        run: mkdir -p Tazq-Backend/publish

      - name: dotnet publish (Only Backend)
        run: |
          dotnet publish Tazq-Backend/Tazq-Backend.csproj -c Release --no-build -o Tazq-Backend/publish

      - name: Debug - Verify Published Files
        run: |
          echo "Checking contents of publish directory..."
          ls -la Tazq-Backend/publish

      - name: Compress Published Files
        run: |
          cd Tazq-Backend/publish
          zip -r ../../backend.zip .
          cd ../..

      - name: Verify ZIP File
        run: |
          if [ ! -f backend.zip ]; then
            echo "ERROR: backend.zip does not exist!"
            exit 1
          fi
          ls -la backend.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend

      - name: Verify Downloaded Files
        run: |
          ls -la backend.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tazq-backend-api'
          package: backend.zip
