# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - tazq-backend-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies (Only Backend)
        run: |
          echo "Restoring only backend dependencies..."
          dotnet restore Tazq-Backend/Tazq-Backend.csproj --force --ignore-failed-sources

      - name: Build Backend Only
        run: |
          echo "Building only backend project..."
          dotnet build Tazq-Backend/Tazq-Backend.csproj --configuration Release --no-restore

      - name: Ensure Publish Directory Exists
        run: mkdir -p Tazq-Backend/publish

      - name: dotnet publish (Only Backend)
        run: |
          echo "Publishing only backend..."
          dotnet publish Tazq-Backend/Tazq-Backend.csproj -c Release -o Tazq-Backend/publish

      - name: Debug - Verify Published Files
        run: |
          echo "Checking contents of publish directory..."
          ls -la Tazq-Backend/publish

      - name: Compress Published Files (Fix for ENOTDIR Error)
        run: |
          echo "Compressing published files..."
          cd Tazq-Backend/publish
          zip -r ../../backend.zip ./*
          echo "Compression completed."

      - name: Verify ZIP File
        run: |
          echo "Checking if ZIP file exists..."
          ls -la backend.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend

      - name: Verify Downloaded Files
        run: |
          echo "Checking if backend.zip exists after download..."
          ls -la backend.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0AC6730E782346CAA2CF0CB7206393B7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E78C97CF44324BF2BFBC240BA4115362 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_976281A093CD4ACF979EF3E6D83AB79F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tazq-backend-api'
          package: backend.zip
