# Azure Web Apps Deploy Pipeline
name: Build and deploy ASP.Net Core app to Azure Web App - tazq-backend-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies (Only Backend)
        run: |
          dotnet restore Tazq-Backend/Tazq-Backend.csproj --force --ignore-failed-sources

      - name: Build Backend Only
        run: |
          dotnet build Tazq-Backend/Tazq-Backend.csproj --configuration Release --no-restore

      - name: Ensure Publish Directory Exists
        run: |
          mkdir -p Tazq-Backend/publish

      - name: dotnet publish (Only Backend)
        run: |
          dotnet publish Tazq-Backend/Tazq-Backend.csproj -c Release -o Tazq-Backend/publish

      - name: Debug - Verify Published Files
        run: |
          echo "Checking contents of publish directory..."
          ls -la Tazq-Backend/publish || (echo "ERROR: Publish directory not found!" && exit 1)

      - name: Compress Published Files
        run: |
          zip -r backend.zip Tazq-Backend/publish
          ls -la backend.zip  # Check if ZIP exists

      - name: Verify ZIP File
        run: |
          if [ ! -f backend.zip ]; then
            echo "ERROR: backend.zip does not exist!"
            exit 1
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: .

      - name: Verify Downloaded Files
        run: |
          if [ ! -f backend.zip ]; then
            echo "ERROR: backend.zip is missing!"
            exit 1
          fi
          ls -la backend.zip

      - name: Unzip Artifact
        run: |
          unzip backend.zip -d Tazq-Backend/publish
          ls -la Tazq-Backend/publish  # Debugging extracted files

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: false

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tazq-backend-api'
          package: Tazq-Backend/publish
